/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AgentResponse: ClassViewer<'AgentResponse', "thought" | "action" | "should_continue" | "final_response">;
    
    Song: ClassViewer<'Song', "title" | "artist" | "genre" | "lyrics">;
    
    ToolCall: ClassViewer<'ToolCall', "tool" | "reasoning" | "parameters">;
    
    
    ToolName: EnumViewer<'ToolName', "SearchProducts" | "GetProductDetails" | "GetProductReviews" | "CompareProducts" | "GetRecommendations" | "AddToCart" | "RemoveFromCart" | "ViewCart" | "AddToWishlist" | "RemoveFromWishlist" | "ViewWishlist" | "PurchaseProduct" | "Checkout" | "ViewOrders" | "None">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AgentResponse","Song","ToolCall",
          ]),
          enums: new Set([
            "ToolName",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AgentResponse = this.tb.classViewer("AgentResponse", [
          "thought","action","should_continue","final_response",
        ]);
        
        this.Song = this.tb.classViewer("Song", [
          "title","artist","genre","lyrics",
        ]);
        
        this.ToolCall = this.tb.classViewer("ToolCall", [
          "tool","reasoning","parameters",
        ]);
        
        
        this.ToolName = this.tb.enumViewer("ToolName", [
          "SearchProducts","GetProductDetails","GetProductReviews","CompareProducts","GetRecommendations","AddToCart","RemoveFromCart","ViewCart","AddToWishlist","RemoveFromWishlist","ViewWishlist","PurchaseProduct","Checkout","ViewOrders","None",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}